Name:		ros-groovy-smd-ardrone2
Version:	0.1.0
Release:	0%{?dist}
Summary:	ROS smd_ardrone2 package

Group:		Development/Tools
License:	BSD
Source0:	%{name}-%{version}.tar.gz

BuildRequires:	ros-groovy-std-srvs,ros-groovy-roscpp,ros-groovy-pluginlib,ros-groovy-sensor-msgs,ros-groovy-image-transport,ros-groovy-geometry-msgs,ros-groovy-tf,ros-groovy-catkin,ros-groovy-nodelet,ffmpeg-devel
Requires:	ros-groovy-std-srvs,ros-groovy-roscpp,ros-groovy-pluginlib,ros-groovy-sensor-msgs,ros-groovy-image-transport,ros-groovy-geometry-msgs,ros-groovy-tf,ros-groovy-nodelet,ffmpeg-devel

%description
Standalone AR.Drone 2 Driver


%prep
%setup -q


%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/groovy/setup.sh" ]; then . "/opt/ros/groovy/setup.sh"; fi
mkdir build && cd build
cmake .. \
	-DCMAKE_VERBOSE_MAKEFILE=ON \
	-DCATKIN_BUILD_BINARY_PACKAGE="1" \
	-DCMAKE_INSTALL_PREFIX="/opt/ros/groovy" \
	-DCMAKE_PREFIX_PATH="/opt/ros/groovy" \
	-DSETUPTOOLS_DEB_LAYOUT=OFF
make %{?_smp_mflags}


%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/groovy/setup.sh" ]; then . "/opt/ros/groovy/setup.sh"; fi
cd build
make install DESTDIR=%{buildroot}


%files
%doc
/opt/ros/groovy


%changelog
* Sat Feb 23 2013 Scott K Logan <logans@cottsay.net> - 0.1.0-0
- autogenerated

